# Generated by Django 5.2 on 2025-05-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_proposed_by_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
