# Generated by Django 5.2 on 2025-05-11 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventparticipation_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='expected_attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, help_text='General Location or Area', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_booking', to='events.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='events.venue')),
            ],
            options={
                'unique_together': {('venue', 'start_time', 'end_time')},
            },
        ),
    ]
