# Generated by Django 5.2 on 2025-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_address',
            field=models.CharField(blank=True, help_text='Full address for geocoding (e.g., 123 Main St, City, Country)', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude (auto-filled via geocoding)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude (auto-filled via geocoding)', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='full_address',
            field=models.CharField(blank=True, help_text='Full Address for geocoding (e.g., 123 Main St, City, Country)', max_length=300),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude (auto-filled via geocoding)', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude (auto-filled via geocoding)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date/time of the event', null=True),
        ),
    ]
