# Generated by Django 5.2 on 2025-05-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_full_address_event_latitude_event_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='longitude',
        ),
        migrations.AddField(
            model_name='venue',
            name='zone',
            field=models.CharField(blank=True, help_text='Zone for proximity (e.g., Downtown, Campus)', max_length=100),
        ),
    ]
