# Generated by Django 5.2 on 2025-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_venue_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='venuebooking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='path/to/default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
