# Generated by Django 5.2 on 2025-05-13 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_options_alter_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='venuebooking',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_bookings', to='events.event'),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.venue'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('coordinator', 'Event Coordinator'), ('setup', 'Setup Crew'), ('registration', 'Registration'), ('technical', 'Technical Support'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['capacity'], name='events_venu_capacit_aca8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='venuebooking',
            index=models.Index(fields=['venue', 'start_time', 'end_time'], name='events_venu_venue_i_7abb7d_idx'),
        ),
    ]
