# Generated by Django 5.2 on 2025-05-14 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_groupmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number.')]),
        ),
    ]
