# Generated by Django 5.2 on 2025-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_event_is_approved_event_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Link to Google Maps location', max_length=500),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
