# Generated by Django 5.2 on 2025-06-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_venue_google_map_link_venue_latitude_venue_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('sports', 'Sports'), ('music', 'Music'), ('program', 'Program'), ('other', 'Other')], default='program', max_length=50),
        ),
    ]
